name = "aispeeds"
main = "index.ts"
compatibility_date = "2025-05-30"
routes = [
  { pattern = "cc.xiaohui.cool", custom_domain = true },
  { pattern = "aispeeds.me", custom_domain = true },
]

# Build configuration for client scripts
[build]
command = "npm run build:client"
watch_dir = "src/client"

[vars]
# Use '*' to allow any host, or a comma-separated list of exact hostnames
# e.g. "images.unsplash.com,cdn.jsdelivr.net"
IMAGE_PROXY_WHITELIST = "*"
# Cache TTL in seconds for proxied images
IMAGE_PROXY_CACHE_TTL = "86400"

# Enable logging
[observability]
enabled = true
head_sampling_rate = 1

# Assets configuration for static files (disabled - using new modular system)
# [assets]
# directory = "./static"
# binding = "ASSETS"
